server:
  port: ${TRAIN_OF_THOUGHTS_PORT:9090}

spring:
  application:
    name: train-of-thoughts
  main:
    banner-mode: OFF
  jpa:
    ## Logs queries to standard-output.
    #show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        generate-ddl: true
        ddl-auto: update
        ## Logs queries to standard-output.
        #show_sql: true
        format_sql: true
        #use_sql_comments: true
        #type: trace
    database: postgresql
  datasource:
    initialization-mode: always
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: postgres
    password: kbox123

## Prints out log entries like 'org.hibernate.type.descriptor.sql.BasicExtractor'
## which are unnecessary. This setting is too generic. We will use the more
## specific one down below.
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace

## Logs queries to a logging framework's log appender such as log-back or log4j.
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

swagger:
  api-info:
    title: KBOX GLOBAL - Train of Thoughts Demo Application
    description: In this web page, you can interact with API resources of Train of Thoughts Demo Application
    version: 0.0.1-SNAPSHOT
    terms-of-service-url: 'https://generator.lorem-ipsum.info/terms-and-conditions'
    contact:
      name: Oguz Erhan Eker
      url: 'https://www.linkedin.com/in/oguzerhaneker/'
      email: 'eker.oguz@gmail.com'
    license: 'Apache License Version 2.0'
    license-url: 'https://www.apache.org/licenses/LICENSE-2.0'
    vendor-extensions:
      -
        name: KBOX GLOBAL
        value: Train of Thoughts Demo Application

train-of-thoughts:
  page-size: 20
  date-time-period: 30
